version: '3.1'
services:
  predis_app:
    image: mikjk/predis_docker:latest
    network_mode: host
    volumes:
      - /home/user/docker_volume/predis/devices:/home/PREDIS_project/devices
    environment:
      - FILE_BASE_PATH=$FILE_BASE_PATH
      - APP_MODE=$APP_MODE
      - CONFIG_FILE_PATH=$CONFIG_FILE_PATH
      - DB_NAME=$DB_NAME
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_PASSWORD
      - DB_PORT=$DB_PORT
      - DB_HOST=$DB_HOST
      - MERCURE_HUB=$MERCURE_HUB
      - MERCURE_TOKEN=$MERCURE_TOKEN
    depends_on:
    - db
  db:
    image: postgres:14.3
    restart: always
    hostname: postgres
    environment:
      - POSTGRES_DB=$DB_NAME
      # So you don't have to use root, but you can if you like
      - POSTGRES_USER=$DB_USER
      # You can use whatever password you like
      - POSTGRES_PASSWORD=$DB_PASSWORD
      # Password for root access
    ports:
      - '5432:5432'
    expose:
      # Opens port 3306 on the container
      - '5432'
      # Where our data will be persisted
    volumes:
      - /home/user/docker_volume/predis/db.sql:/docker-entrypoint-initdb.d/db.sql
      - postgres_volume:/var/lib/postgresql
  post_ops:
    image: mikjk/post_ops:latest
    environment:
      - MERCURE_HUB=$MERCURE_HUB
      - MERCURE_TOKEN=$MERCURE_TOKEN
      - MERCURE_TOPIC=$MERCURE_TOPIC
      - AZURE_CONNECTION_STRING= $AZURE_CONNECTION_STRING
    volumes:
      - /home/user/docker_volume/predis/devices:/home/PREDIS_project/devices
  mercure:
    image: dunglas/mercure
    restart: unless-stopped
    environment:
      - SERVER_NAME=:80
      - MERCURE_PUBLISHER_JWT_KEY=$MERCURE_JWT_KEY
      - MERCURE_SUBSCRIBER_JWT_KEY=$MERCURE_JWT_KEY
      - MERCURE_EXTRA_DIRECTIVES= |
        anonymous
        cors_origins *
    # Uncomment the following line to enable the development mode
    #command: /usr/bin/caddy run --config /etc/caddy/Caddyfile.dev
    ports:
      - '8001:80'
    volumes:
      - mercure_data:/data
      - mercure_config:/config
volumes:
  mercure_data:
  mercure_config:
  postgres_volume: